version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    networks:
      - node_app
    depends_on:
      - app1
      - app2
      - app3


  app1:
    container_name: app1
    build: ./node1
    ports:
    - "3000:3000"
    networks:
      - node_app

  app2:
    container_name: app2
    build: ./node2
    ports:
    - "3001:3001"
    networks:
      - node_app

  app3:
    container_name: app3
    build: ./node3
    ports:
    - "3002:3002"
    networks:
      - node_app

networks:
  node_app:
    driver: bridge
