name: Docker Build and Test and Push to DockerHub
on:
  push:
    branches: [ "node" ]
  pull_request:
    branches: [ "node" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Docker 
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Iterate over Node.js apps and build Docker images
        run: |
         for app in nodeapp1 nodeapp2 nodeapp3; do
           if [ -f ./$app/Dockerfile ]; then
             docker build -t sainiji/$app:latest ./$app
             docker push sainiji/$app:latest
           else
             echo "Dockerfile not found in ./$app directory. Skipping..."
           fi
         done
