name: Docker Build and Test and Push to DockerHub
on:
  push:
    branches: [ "node" ]
  pull_request:
    branches: [ "node" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Docker 
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Iterate over Node.js apps and build Docker images
        run: |
         for app in node1 node2 node3; do
           if [ -f ./$app/Dockerfile ]; then
             docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$app:v1 ./$app
             docker push ${{ secrets.DOCKERHUB_USERNAME }}/$app:v1
           else
             echo "Dockerfile not found in ./$app directory. Skipping..."
           fi
         done
         
      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.20.0/trivy_0.20.0_Linux-64bit.tar.gz
          tar zxvf trivy_0.20.0_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/
          
      - name: Run Trivy scan
        run: |
          trivy --exit-code 1 ${{ secrets.DOCKERHUB_USERNAME }}/node1:v1
          trivy --exit-code 1 ${{ secrets.DOCKERHUB_USERNAME }}/node2:v1
          trivy --exit-code 1 ${{ secrets.DOCKERHUB_USERNAME }}/node3:v1
