name: Docker Build, Test, and Push to DockerHub
on:
  push:
    branches: [ "node" ]
  pull_request:
    branches: [ "node" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Docker 
        uses: docker/setup-buildx-action@v1
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Iterate over Node.js apps and build Docker images
        run: |
          for app in node1 node2 node3; do
            if [ -f ./$app/Dockerfile ]; then
              docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$app:v1 ./$app
              docker push ${{ secrets.DOCKERHUB_USERNAME }}/$app:v1
            else
              echo "Dockerfile not found in ./$app directory. Skipping..."
            fi
          done
          
      - name: Run Trivy scan
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy ${{ secrets.DOCKERHUB_USERNAME }}/node1:v1
          exit_code=$?
          if [ $exit_code -eq 0 ]; then
            echo "No vulnerabilities found."
          else
            echo "Vulnerabilities found. Exit code: $exit_code"
          fi
